### ISSUE TITLE
bug: On refresh the loggedin user didn't persist

### ISSUE THREAD

**Issue by geekyharsh05** [adrianhajdin/storage_management_solution#1]
When logging in and after refreshing the page it logs out automatically.

**Comment by pantharshit007** [comment]
> When logging in and after refreshing the page it logs out automatically.

not happening in my case though

**Comment by geekyharsh05** [comment]
https://github.com/user-attachments/assets/8987b9f4-5650-4b65-bcd9-9d8bac267e98

**Comment by AnasSiddiqui18** [comment]
Hello 👋,
Hope you're fine and doing great. I have checked the application, it's working perfectly fine. I am also attaching a video so you can also check it. 

https://github.com/user-attachments/assets/ee0d30dd-eddb-4c73-9151-0f1b3f9f097d



@geekyharsh05

**Comment by shemaikuzwe** [comment]
check in cookie storage if appwrite session secret is there and in your createSesssionclient if you are properly getting it
